on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        container:
          - alpine-openssl
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/setup-qemu-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.container }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/e3b0c442/${{ matrix.container}}:${{ github.sha }}
            ghcr.io/e3b0c442/${{ matrix.container}}:latest